- src/main/kotlin/no/nav/familie/ks/barnehagelister/kontrakt/Barnehagelistekontrakt.kt
Justert api etter diskusjon på fredag + startet på dokumentasjon av felter i api
> Justert api etter diskusjon på fredag

- src/main/kotlin/no/nav/familie/ks/barnehagelister/interceptor/MaskinportenTokenLoggingInterceptor.kt
- src/main/kotlin/no/nav/familie/ks/barnehagelister/rest/ApiExceptionHandler.kt
- src/main/kotlin/no/nav/familie/ks/barnehagelister/rest/BarnehagelisteService.kt
- src/main/kotlin/no/nav/familie/ks/barnehagelister/rest/BarnehagelisterController.kt
- src/main/kotlin/no/nav/familie/ks/barnehagelister/rest/DefaultBarnehagelisterController.kt
- src/main/resources/application.yaml
- src/test/kotlin/no/nav/familie/ks/barnehagelister/rest/UnprotectedBarnehagelisteController.kt
- **debug headers**
- **Lagt til errorresponse og handler for feilmeldinger. Valgt å bruk ProblemDetail RFC9457**
- **Kjør dev-profilen uten at man trenger maskinporten-token**
> Lagt til error response og mulighet til å teste lokalt uten maskinporten-token

- pom.xml
- src/main/kotlin/no/nav/familie/ks/barnehagelister/domene/Barnehagelister.kt
- src/main/kotlin/no/nav/familie/ks/barnehagelister/kontrakt/Barnehagelistekontrakt.kt
- src/main/kotlin/no/nav/familie/ks/barnehagelister/rest/ApiExceptionHandler.kt
- src/main/kotlin/no/nav/familie/ks/barnehagelister/rest/BarnehagelisteService.kt
- src/main/kotlin/no/nav/familie/ks/barnehagelister/rest/BarnehagelisteTestdata.kt
- src/main/kotlin/no/nav/familie/ks/barnehagelister/rest/BarnehagelisterController.kt
- src/test/kotlin/no/nav/familie/ks/barnehagelister/DbContainerInitializer.kt
- src/test/kotlin/no/nav/familie/ks/barnehagelister/rest/BarnehagelisteControllerTest.kt
Tester og validering i SkjemaV1
> Validering med valideringstester

- src/main/kotlin/no/nav/familie/ks/barnehagelister/rest/BarnehagelisteService.kt
- src/main/kotlin/no/nav/familie/ks/barnehagelister/task/MottattBarnehagelisteTask.kt
Tom task som per nå bare setter status til FERDIG
> Task for å motta barnehageliste

- src/main/kotlin/no/nav/familie/ks/barnehagelister/kontrakt/Barnehagelistekontrakt.kt
- src/test/kotlin/no/nav/familie/ks/barnehagelister/rest/BarnehagelisteTestdata.kt
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-23254
Vi ønsker å fjerne endringstype fra apiet vårt da det ikke blir brukt.
> Vi fjerner ubrukt felt fra apiet vårt

- .deploy/nais/nais-preprod.yaml
- .deploy/nais/nais-prod.yaml
Legg til `delegationSource: altinn` i Maskinporten-configen i Nais-filene, for å kunne delegere tilgang til apiet
> Legg til delegationSource i Maskinporten-config

- .deploy/nais/nais-preprod.yaml
- .deploy/nais/nais-prod.yaml
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-23253)
For å kunne nå applikasjonen via delegebart api må vi applikasjonen "accessibleForAll" slik at konsumenter/kommuner kan nå oss.
> legg til accessibleForAll i maskinporten

- pom.xml
- src/main/kotlin/no/nav/familie/ks/barnehagelister/interceptor/MaskinportenTokenLoggingInterceptor.kt
- src/main/kotlin/no/nav/familie/ks/barnehagelister/interceptor/RequestParser.kt
- src/main/kotlin/no/nav/familie/ks/barnehagelister/rest/ApiExceptionHandler.kt
- src/main/kotlin/no/nav/familie/ks/barnehagelister/rest/BarnehagelisterController.kt
- src/main/kotlin/no/nav/familie/ks/barnehagelister/rest/DefaultBarnehagelisterController.kt
- src/main/kotlin/no/nav/familie/ks/barnehagelister/rest/GodkjenteLeverandører.kt
- src/main/resources/application-preprod.yaml
- src/test/kotlin/no/nav/familie/ks/barnehagelister/rest/UnprotectedBarnehagelisteController.kt
- src/test/resources/application-dev.yaml
Ønsker kun å ta imot barnehagelister fra forhåndsgodkjente leverandører.
Status og Ping er fortsatt åpent for "alle". Gi en lyd hvis noen tenker at det er dumt.
> begrens tilgang til API på leverandør

- src/main/kotlin/no/nav/familie/ks/barnehagelister/rest/BarnehagelisterController.kt
- src/main/kotlin/no/nav/familie/ks/barnehagelister/rest/ValideringsfeilException.kt
oversett operationId til engelsk
> fjern norske endepunkt

- src/main/kotlin/no/nav/familie/ks/barnehagelister/rest/dto/KindergartenRequestDto.kt
- src/main/kotlin/no/nav/familie/ks/barnehagelister/rest/dto/PersonRequestDto.kt
- src/main/kotlin/no/nav/familie/ks/barnehagelister/validering/FødselsnummerValidator.kt
- src/main/kotlin/no/nav/familie/ks/barnehagelister/validering/OrganisasjonsnummerValidator.kt
- src/test/kotlin/no/nav/familie/ks/barnehagelister/rest/UnprotectedBarnehagelisteControllerIntegrasjonTest.kt
- src/test/kotlin/no/nav/familie/ks/barnehagelister/testdata/FormV1DtoTestdata.kt
- src/test/kotlin/no/nav/familie/ks/barnehagelister/testdata/SkjemaV1TestData.kt
- src/test/kotlin/no/nav/familie/ks/barnehagelister/validering/FødselsnummerValidatorTest.kt
- src/test/kotlin/no/nav/familie/ks/barnehagelister/validering/OrganisasjonsnummerValidatorTest.kt
- **Validering av Organisasjonsnummer**
- **Validering av fødselsnummer**
Lagt til validatorer som sjekker om fødselsnummer og orgnr er gyldige verdier. Slår ikke opp i register for å sjekke om at numrene faktisk er knyttet til en bedrift eller person, slik at ingen uvedkommende skal kunne få vasket fødselsnummer/orgnr mot tjenesten vår.
> Validering av OrgNr og Fødselsnummer

- .github/workflows/build-pr.yml
- src/main/kotlin/no/nav/familie/ks/barnehagelister/domene/Barnehagebarn.kt
- src/main/kotlin/no/nav/familie/ks/barnehagelister/domene/SkjemaV1.kt
- src/main/kotlin/no/nav/familie/ks/barnehagelister/kafka/BarnehagebarnDto.kt
- src/main/kotlin/no/nav/familie/ks/barnehagelister/kafka/BarnehagebarnKS.kt
- src/main/kotlin/no/nav/familie/ks/barnehagelister/kafka/BarnehagebarnKafkaProducer.kt
- src/main/kotlin/no/nav/familie/ks/barnehagelister/repository/BarnehagebarnRepository.kt
- src/test/kotlin/no/nav/familie/ks/barnehagelister/domene/SkjemaV1Test.kt
- src/test/kotlin/no/nav/familie/ks/barnehagelister/testdata/SkjemaV1TestData.kt
KS trenger ikke organisasjonsnummer
Legger til en egen kontrakt for hva vi sender til KS slik at det er lett å legge til flere felter i Barnehagebarn
> Ikke send med organisasjonsnummer til KS

- src/main/kotlin/no/nav/familie/ks/barnehagelister/config/ApplicationConfig.kt
- src/main/kotlin/no/nav/familie/ks/barnehagelister/rest/dto/KindergartenRequestDto.kt
- src/main/kotlin/no/nav/familie/ks/barnehagelister/rest/dto/PersonRequestDto.kt
- src/test/kotlin/no/nav/familie/ks/barnehagelister/rest/UnprotectedBarnehagelisteControllerIntegrasjonTest.kt
- **Setter eksempeltverdier til verdier som validerer**
- **Duplikate fields i request vil nå resultere i en bad request feil**
> Kast valideringsfeil hvis input har duplikate property

- pom.xml
- src/main/kotlin/no/nav/familie/ks/barnehagelister/domene/Barnehagebarn.kt
- src/main/kotlin/no/nav/familie/ks/barnehagelister/domene/Barnehageliste.kt
- src/main/kotlin/no/nav/familie/ks/barnehagelister/domene/BarnehagelisteValideringsfeil.kt
- src/main/kotlin/no/nav/familie/ks/barnehagelister/repository/BarnehagelisteValideringsfeilRepository.kt
- src/main/kotlin/no/nav/familie/ks/barnehagelister/rest/ApiExceptionHandler.kt
- src/main/kotlin/no/nav/familie/ks/barnehagelister/rest/DefaultBarnehagelisteController.kt
- src/main/kotlin/no/nav/familie/ks/barnehagelister/rest/JsonValideringsfeilException.kt
- src/main/kotlin/no/nav/familie/ks/barnehagelister/rest/ProblemDetailMedCallIdOgErrors.kt
- src/main/kotlin/no/nav/familie/ks/barnehagelister/rest/dto/KindergartenlistResponse.kt
- src/main/kotlin/no/nav/familie/ks/barnehagelister/service/BarnehagelisteService.kt
- src/main/kotlin/no/nav/familie/ks/barnehagelister/task/LesBarnehagelisteTask.kt
- src/main/kotlin/no/nav/familie/ks/barnehagelister/task/PeriodeOverlappValideringTask.kt
- src/main/kotlin/no/nav/familie/ks/barnehagelister/task/ValiderBarnehagelisteTask.kt
- src/main/kotlin/no/nav/familie/ks/barnehagelister/validering/PeriodeValidator.kt
- src/main/resources/db/migration/V7__BarnehagelisteValideringsFeil.sql
- src/test/kotlin/no/nav/familie/ks/barnehagelister/domene/BarnehagelisteServiceTest.kt
- src/test/kotlin/no/nav/familie/ks/barnehagelister/rest/DefaultBarnehagelisteControllerEnhetTest.kt
- src/test/kotlin/no/nav/familie/ks/barnehagelister/rest/UnprotectedBarnehagelisteController.kt
- src/test/kotlin/no/nav/familie/ks/barnehagelister/rest/UnprotectedBarnehagelisteControllerIntegrasjonTest.kt
- src/test/kotlin/no/nav/familie/ks/barnehagelister/task/PeriodeOverlappValideringTaskTest.kt
- src/test/kotlin/no/nav/familie/ks/barnehagelister/validering/PeriodeValidatorKtTest.kt
[NAV-24060](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-24060)
Validerer at perioder ikke overlapper i en barnehagelist. Denne valideringen skjer før splitting og lagring ned. Periodene blir likevel sendt til KS-sak, men en leverandør vi få en liste som ikke validerer
> Validering perioder internt i en liste

- .deploy/nais/nais-preprod.yaml
- .deploy/nais/nais-prod.yaml
- .github/workflows/build-and-deploy-preprod.yml
Oppsett av de eksterne ingressene. De får kun tilgang til swagger og /api/kindergarten
> Oppsett av eksterne ingresser

- src/main/kotlin/no/nav/familie/ks/barnehagelister/config/SwaggerDocumentationConfig.kt
Oppdatert swagger dokumentasjon. Lagt til beskrivelse av tjenesten og de vanligste feilmeldingene man kan få
- **oppdater beskrivelse av applikasjonen i openapi**
- **Oppdatert dokumentasjon**
> Forbedring av dokumentasjon

- src/main/kotlin/no/nav/familie/ks/barnehagelister/config/SwaggerDocumentationConfig.kt
La inn beskrivelse av enkle testkriterier som bør gjøres av nye leverandører før de går i prod
> Added test criteria before going to production

- src/main/resources/application-preprod.yaml
- src/main/resources/application-prod.yaml
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-24715
Vi må legge til visma sitt nye org nr ref: https://nav-it.slack.com/archives/C07LYNSNKNJ/p1742380205814549
> Legg til nytt visma orgnummer

- src/main/kotlin/no/nav/familie/ks/barnehagelister/config/SwaggerDocumentationConfig.kt
- src/main/kotlin/no/nav/familie/ks/barnehagelister/rest/dto/ChildInformationRequestDto.kt
dokumentasjonen vår når det kommer til at man kan sende inn flere perioder av det samme barnet i én liste er ikke så god så legger til litt bedre beskrivelse
> legg til bedre beskrivelse av perioder

- .nais/app-dev.yaml
- .nais/app-prod.yaml
- src/main/resources/logback-spring.xml
https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-25299
- **Lagt til team logs**
https://docs.nais.io/observability/logging/how-to/team-logs/#__tabbed_1_1
Fra Log explorer
URL:
https://console.cloud.google.com/logs/query;query=resource.labels.container_name%3D%22familie-ks-barnehagelister%22;cursorTimestamp=2025-05-26T10:55:20.828024978Z?authuser=1&inv=1&invt=Abyaxg&project=teamfamilie-dev-ae07
> Tester ut teamlogs

- src/main/kotlin/no/nav/familie/ks/barnehagelister/config/SwaggerDocumentationConfig.kt
- src/main/kotlin/no/nav/familie/ks/barnehagelister/rest/dto/KindergartenlistResponse.kt
litt bedre beskrivelser av felter
> eksempel-url for status-endepunkt
